### ISSUE TITLE
Cannot figure out how to compile project

### ISSUE THREAD

**Issue by MerryPlace** [DeflatedPickle/Quiver#10]
This seems like a great program, and I would really love to try it out, but I cannot figure out how to compile it for the life of me. I'm very much a beginner with python so I've spent about 2 hours now trying to figure out how to get this program running. At this point I've given up after approaching this from as many angles as stackoverflow would steer me to no avail... 
1. trying to run `python [path to folder]` in my command prompt
2. installing pyinstaller so that I can run the setup.bat file
3. clicking on every .py file in the folder and praying (again I'm a total beginner with python)

I would appreciate it more than you know if anyone could spell out for me how to get this running.
attached is a screenshot of the folder after unzipping:

![47f0d0dd24131457583c2b065c5a4336](https://user-images.githubusercontent.com/38738663/54173015-8f167280-4456-11e9-855e-4b442bab145e.png)

**Comment by MerryPlace** [comment]
I decided to try again and woooowee is this a handful. I can successfully get a build but it doesn't open so I looked through the logs and I can see that I'm missing an insane amount of files. All but one of them are outdated files in System32 and SysWOW64's downlevel that I had to put back into them (which is really really weird). and then one other error, 
> Hidden import 'nbt.world' not found

which I am absolutely stumped on. No idea what this file is or where to find it but pyinstaller can't so RIP.
Maybe my computer is just fucked up beyond belief or something but if every user is facing these same errors and you aren't able to make any updates you should probably take this project off of github or put a disclaimer. I can't believe I spent so much time on this.

**Comment by DeflatedPickle** [comment]
@NoahOrtega , I am so very sorry for wasting your time! I never checked this project and thought it had been completely forgotten about. I'll be re-making it and I'll include build instructions this time!

Honestly, I was just a terrible programmer when I made this, I didn't think anyone would use it and I'm not very good socially, so I've been pretty scared to reply to issues in the past.

**Comment by MerryPlace** [comment]
@DeflatedPickle Missed your reply sorry, really happy to see you're still working on this project after so much time! If you ever need a bug tester hmu 👍

**Comment by DeflatedPickle** [comment]
@NoahOrtega, I wasn't working on it for the longest time, but I've had more requests than I thought to continue it. The re-write has already taken place, and I think I moved the master branch to it. This time, it's in Kotlin using Swing, has a dockable layout and plugin and per-plugin config support, though it isn't ready for release just yet.

I'll put up testing/building instructions, and I'll put together a wiki once it's out.
