### ISSUE TITLE
Default Photo Editing Software

### ISSUE THREAD

**Issue by thatdumbdevit** [DeflatedPickle/Quiver#106]
Hi,
When I click on the pencil icon to edit a texture, it opens Paint. What if I want to use another software to edit it, like Gimp or Photoshop?

**Comment by DeflatedPickle** [comment]
Any "edit" action that Quiver performs to open a program uses *your* system default program associated with that file type. So if your system default is Paint, it'll open it in that

But there is a solution! Given you're using `v1.10.0`, you can click on the drop down of the "open" button, hover over "open in" and then click "add application". You will then be greeted by a dialog where you can assign a logical name for the program, the path to it's executable, any program arguments you should need and the file types that this program should open. I'll add this to the wiki when I can, though my desk is currently filled with things whilst I put up shelves so I only have access to my Chromebook that has mild troubles smoothing fonts of Java apps opened via the embeded Linux

**Comment by thatdumbdevit** [comment]
> Any "edit" action that Quiver performs to open a program uses _your_ system default program associated with that file type. So if your system default is Paint, it'll open it in that
> 
> But there is a solution! Given you're using `v1.10.0`, you can click on the drop down of the "open" button, hover over "open in" and then click "add application". You will then be greeted by a dialog where you can assign a logical name for the program, the path to it's executable, any program arguments you should need and the file types that this program should open. I'll add this to the wiki when I can, though my desk is currently filled with things whilst I put up shelves so I only have access to my Chromebook that has mild troubles smoothing fonts of Java apps opened via the embeded Linux

What should I put in "args"? I'm going to use GIMP.

**Comment by DeflatedPickle** [comment]
So the arguments part is for any CLI arguments that the program can take that can modify the editing experience. It can be none, but some programs make heavy use of flags for useful settings. To find these, you can either read the documentation, `man` page or open a terminal and type the program name followed by `-h` or `--help`. In this case, `gimp -h`

From running this, I can see that `-a` might be nice, `-c` can get rid of annoying error dialogues, `--display` can make Gimp open on a specific window, etc. Most arguments are for debugging, but some can help more than others in tweaking the specific user experience

**Comment by DeflatedPickle** [comment]
@thatdumbdevit, I've just checked the code on how this works and it turns out you do need to pass one argument, which for most programs should just be `{file}` though some might want `-o {file}` or `--open {file}`. It's up to the program dev to decide on, which is why it's up to the user to enter these bits in Quiver. Anyway `{file}` is then replaced by Quiver with the currently selected file and `{dir}` is replaced by the currently selected directory. I'll make sure this is added to the text box when the dialog is opened for the next release
