### ISSUE TITLE
When I open the .bat file it closes by itself, what can it be?

### ISSUE THREAD

**Issue by thiagogebrimm** [DeflatedPickle/Quiver#116]
**Describe the bug**
When I open the .bat file it closes by itself, what can it be?

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on .bat file

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.10

**Additional context**

**Comment by DeflatedPickle** [comment]
I need to write this in the README but if you need the log output, until I add in some log dump, you can start a terminal either in the same directory as the start script or anywhere else and `cd` your way to the start script. Anyway, my guess is this is related to you running it with a JRE newer than Java 8. The README specifies it must be run with Java 8, it is not saying that lightly. This is an ongoing issue that I am looking to resolve though I invite anyone who wants to, to have a go at tweaking the code. I'll make an issue for Java 9+ support
