### ISSUE TITLE
1.10.0 crashes with Ubuntu 20.04

### ISSUE THREAD

**Issue by AFCMS** [DeflatedPickle/Quiver#152]
**Describe the bug**
![image](https://user-images.githubusercontent.com/61794590/155174008-ffd453b7-7a79-4615-a341-4ef7271c4b19.png)
![image](https://user-images.githubusercontent.com/61794590/155174257-1d079b71-0b5f-4f9e-a598-e7cd5ad4cea7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Comment by AlexTMjugador** [comment]
I think that error might be caused due to the distro shipping with a newer Java version. Try using Java 8. There is more information in this tracking issue: https://github.com/DeflatedPickle/Quiver/issues/117

**Comment by AFCMS** [comment]
Thanks, it works!
