### ISSUE TITLE
There is no quiver.exe

### ISSUE THREAD

**Issue by Bluestripe12** [DeflatedPickle/Quiver#9]
There is no quiver.exe nor is there any in depth instructions, either get some in depth instructions if it's not a bug or fix the missing exe

**Comment by Azrael-1123** [comment]
it isn't a bug, just compile the code.

**Comment by BrayXKun** [comment]
how does one compile the code to get the .exe?

**Comment by DeflatedPickle** [comment]
@Bluestripe12, of course there isn't an EXE in the *source*, it;s the *source* of the project, not the *releases* of the project. Please, use one of the releases in the releases tab.

But build instructions are a good idea, I'll put some in. But it's pretty much just going to be; install Python, install dependencies, run `setup.bat` (which really should be named "build.bat").

Thanks for chiming in @ichbineinNerd. This might be helpful for you too @BrayXKun.
